In [2]:
import numpy as np

**Valid Sudoku**

# Creating the Sudoku by numpy module

In [3]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

# checking whether the sum of rows is equals to 45

In [11]:
b=np.sum(s,axis=1)
for i in b:
    if i!=45:
        print('Not a sudoku')
        break
else:
    print("It is sudoku because sum of rows is 45: row's wise")
    

It is sudoku because sum of rows is 45: row's wise


# checking whether the sum of colum is equals to 45

In [10]:
c=np.sum(s,axis=1)
for i in c:
    if i!=45:
        print('Not a sudoku')
        break
else:
    print("It is sudoku because sum of colum is 45: colum wise")

It is sudoku because sum of colum is 45: colum wise


In [8]:
#splitting the rows
np.split(s,9)

[array([[5, 3, 4, 6, 7, 8, 9, 1, 2]]),
 array([[6, 7, 2, 1, 9, 5, 3, 4, 8]]),
 array([[1, 9, 8, 3, 4, 2, 5, 6, 7]]),
 array([[8, 5, 9, 7, 6, 1, 4, 2, 3]]),
 array([[4, 2, 6, 8, 5, 3, 7, 9, 1]]),
 array([[7, 1, 3, 9, 2, 4, 8, 5, 6]]),
 array([[9, 6, 1, 5, 3, 7, 2, 8, 4]]),
 array([[2, 8, 7, 4, 1, 9, 6, 3, 5]]),
 array([[3, 4, 5, 2, 8, 6, 1, 7, 9]])]

In [12]:
#slicing the specific matrix 
s[:3,:3]

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [13]:
#creating the 3*3 matrix from the existing array
for i in range(0,9,3):
    for j in range(0,9,3):
        if i==9:
            break
        print(s[i:i+3,j:j+3]) 

[[5 3 4]
 [6 7 2]
 [1 9 8]]
[[6 7 8]
 [1 9 5]
 [3 4 2]]
[[9 1 2]
 [3 4 8]
 [5 6 7]]
[[8 5 9]
 [4 2 6]
 [7 1 3]]
[[7 6 1]
 [8 5 3]
 [9 2 4]]
[[4 2 3]
 [7 9 1]
 [8 5 6]]
[[9 6 1]
 [2 8 7]
 [3 4 5]]
[[5 3 7]
 [4 1 9]
 [2 8 6]]
[[2 8 4]
 [6 3 5]
 [1 7 9]]


**General Questions**

In [132]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [133]:
#Get the shape of the matrix.
s.shape
data.shape

(5, 3)

In [96]:
#Find the average age of students.
np.mean(data[:,0])

18.4

In [86]:
#Extract Math marks of all students.
np.mean(data[:,1])

81.6

In [87]:
#Find the highest Science mark.
np.max(data[:,2])

95

In [88]:
#Get details of the student who scored more than 90 in Math.
data[data[:,1]>90]

array([[19, 92, 88]])

In [89]:
#Increase Math marks of all students by 5.
data[:,1]+5

array([90, 97, 81, 70, 95])

In [114]:
#Find how many students are younger than 19.
len(data[data[:,0]<19])

3

In [91]:
#Calculate the average marks in each subject (column-wise mean).
np.mean(data[:,1:],axis=0)

array([81.6, 83.2])

In [121]:
#Get data of students who scored at least 80 in both subjects.
data[(data[:,1]>80) & (data[:,2]>80)]

array([[19, 92, 88],
       [20, 90, 85]])

In [136]:
#Replace all Science marks < 75 with 0.
data[:,2][data[:,2]<=75]=0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])